(()=>{'use strict';const D=window.LQ_DATA;const $=s=>document.querySelector(s);const profileKey=document.body.dataset.profile||'main';const P=D.profiles[profileKey]||D.profiles.main;let active=null,qIndex=0,score=0;const key=`lq3:${profileKey}:history`;let history=JSON.parse(localStorage.getItem(key)||'[]');
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#profile').innerHTML=`<div><span class="badge">${esc(P.level)}</span><h2>${esc(P.name)}</h2><p>Choose a learning center. 选择学习中心。Wähle ein Lernzentrum.</p></div><div><b>⭐ ${history.reduce((a,x)=>a+x.score,0)}</b><br><small>Total stars</small></div>`;
$('#centers').innerHTML=D.centers.map(c=>`<article class="card" data-id="${c.id}"><div class="icon">${c.icon}</div><h3>${c.title}</h3><p>${c.desc}</p><div class="chips">${c.chips.map(x=>`<span class="chip">${x}</span>`).join('')}</div></article>`).join('');
document.querySelectorAll('.card').forEach(x=>x.addEventListener('click',()=>start(x.dataset.id)));$('#parentBtn').addEventListener('click',showParent);
function start(id){active=D.centers.find(c=>c.id===id);qIndex=0;score=0;$('#parent').classList.add('hidden');$('#lesson').classList.remove('hidden');renderQ();$('#lesson').scrollIntoView({behavior:'smooth'});}
function renderQ(){const c=active;if(qIndex>=c.questions.length)return finish();const q=c.questions[qIndex];$('#lesson').innerHTML=`<button id="back">← Centers</button><h2>${c.icon} ${c.title}</h2><div class="bar"><i style="width:${qIndex/c.questions.length*100}%"></i></div><div class="question">${qIndex+1}. ${esc(q[0])}</div><div class="answers">${q[1].map((a,i)=>`<button data-a="${i}">${esc(a)}</button>`).join('')}</div><div id="feedback"></div>`;$('#back').onclick=()=>$('#lesson').classList.add('hidden');document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>answer(b,Number(b.dataset.a),q));}
function answer(btn,i,q){document.querySelectorAll('[data-a]').forEach(b=>b.disabled=true);const good=i===q[2];if(good){score++;btn.classList.add('ok')}else{btn.classList.add('bad','wrong');document.querySelector(`[data-a="${q[2]}"]`).classList.add('ok')}$('#feedback').innerHTML=`<div class="feedback"><b>${good?'✓ Correct! +1 ⭐':'↻ Try to understand why.'}</b><p>${esc(q[3])}</p><button id="next">${qIndex+1===active.questions.length?'Finish':'Next →'}</button></div>`;$('#next').onclick=()=>{qIndex++;renderQ()};}
function finish(){history.push({date:new Date().toISOString(),center:active.title,score,total:active.questions.length});localStorage.setItem(key,JSON.stringify(history.slice(-100)));$('#lesson').innerHTML=`<h2>🎉 Quest complete!</h2><p>You earned <b>${score} / ${active.questions.length} ⭐</b>.</p><button id="again">再来一次 · Play again</button>`;$('#again').onclick=()=>start(active.id);}
function showParent(){const rows=history.slice().reverse().map(x=>`<tr><td>${new Date(x.date).toLocaleString()}</td><td>${esc(x.center)}</td><td>${x.score}/${x.total}</td></tr>`).join('');$('#lesson').classList.add('hidden');$('#parent').classList.remove('hidden');$('#parent').innerHTML=`<h2>家长学习记录 · Parent Log</h2><div class="stats"><div class="stat"><b>${history.length}</b><br>Sessions</div><div class="stat"><b>${history.reduce((a,x)=>a+x.score,0)}</b><br>Stars</div><div class="stat"><b>${history.length?Math.round(100*history.reduce((a,x)=>a+x.score,0)/history.reduce((a,x)=>a+x.total,0)):0}%</b><br>Accuracy</div></div><div style="overflow:auto"><table width="100%" cellpadding="10"><thead><tr><th>Date</th><th>Center</th><th>Score</th></tr></thead><tbody>${rows||'<tr><td colspan="3">No learning record yet.</td></tr>'}</tbody></table></div><button id="clear">清空本机记录</button>`;$('#clear').onclick=()=>{if(confirm('Clear local learning records?')){history=[];localStorage.removeItem(key);showParent()}};$('#parent').scrollIntoView({behavior:'smooth'});}
})();
