window.LQ_DATA={
profiles:{main:{name:'Kevin & Camilla',level:'G1–G6 · multilingual'},harry:{name:'Harry',level:'Personal learning path'}},
centers:[
{id:'chinese',icon:'📚',title:'语文 Chinese 中文',desc:'人教版方向：识字、词语、阅读理解、古诗与表达。',chips:['G1–G6','读写','古诗'],questions:[['“春眠不觉晓”的下一句是？',['处处闻啼鸟','花落知多少','夜来风雨声'],0,'《春晓》：春眠不觉晓，处处闻啼鸟。'],['“跨越”的“越”更接近哪个意思？',['超过、越过','停止','隐藏'],0,'“越”可以表示跨过、超过。']]},
{id:'english',icon:'🔤',title:'English 英语 Englisch',desc:'Phonics, vocabulary, comprehension and retelling.',chips:['G1–G6','Phonics','Reading'],questions:[['Which word has the long /a/ sound?',['cake','cat','map'],0,'The silent-e pattern in cake makes the vowel say its name.'],['What should a retelling include?',['First → Next → Then → Finally','Only the title','Only one word'],0,'Sequence words help organize a clear retelling.']]},
{id:'raz',icon:'🚀',title:'RAZ Reading Center',desc:'AA–F 分级阅读训练：理解、Why 问题、顺序与复述。',chips:['AA–F','Comprehension','Retelling'],questions:[['After reading, which question checks a reason?',['Why did it happen?','What color is the cover?','How many pages?'],0,'“Why” questions test causal understanding.'],['Which order is best for retelling?',['First → Next → Last','Last → First → Maybe','Random order'],0,'Retelling should preserve event sequence.']]},
{id:'math',icon:'🧠',title:'数学 Math Mathematik',desc:'数感、等量代换、单位换算、应用题与图形思维。',chips:['G1–G6','数感','奥数'],questions:[['If ★ + ★ = 14, what is ★?',['7','14','28'],0,'Two equal stars total 14, so each star is 14 ÷ 2 = 7.'],['2 m = ? cm',['200','20','2000'],0,'1 m = 100 cm, so 2 m = 200 cm.']]},
{id:'german',icon:'🇩🇪',title:'Deutsch 德语 德文',desc:'A1–A2 Wortschatz, Lesen und Satzverständnis.',chips:['A1–A2','Lesen','Wortschatz'],questions:[['Was bedeutet “der Hund”?',['dog','cat','bird'],0,'“der Hund” means “the dog”.'],['Ich ___ acht Jahre alt.',['bin','bist','seid'],0,'With “ich”, the correct form of sein is “bin”.']]},
{id:'science',icon:'🔬',title:'Science 科学 Naturkunde',desc:'生命、物质、地球与基础科学探究。',chips:['G1–G6','Inquiry','STEM'],questions:[['What do plants need for photosynthesis?',['Light','Plastic','Metal'],0,'Plants use light energy to make food.'],['Which state of matter keeps its own shape?',['Solid','Liquid','Gas'],0,'A solid normally keeps a fixed shape.']]}
]};
